---
stages:
  - test
  - build
  - review
  - release

include:
  - { project: fsrvcorp/templates, file: templates/language/dotnet.yml, ref: 1.0.10 }
  - { project: fsrvcorp/templates, file: templates/release/kaniko.yml, ref: 1.0.10 }
  - { project: fsrvcorp/templates, file: templates/release/semver.yml, ref: 1.0.10 }
  - { project: fsrvcorp/ci-templates, file: kubernetes-review.yaml }

variables:
  KUBE_BASE_DIR: "${CI_PROJECT_DIR}/test/IntegrationTest/.kube"
  KANIKO_ARGS: --context ${CI_PROJECT_DIR}/src/GitlabChamp --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} --build-arg REPO_VERSION=${REPO_VERSION}
  CONTAINER_FILE_LOCATION: ${CI_PROJECT_DIR}/src/GitlabChamp/Dockerfile
  SEMVER_PREFIX: "v"

.dotnet_template_defaults:
  stage: test
.kaniko_template_defaults:
  stage: build
  needs:
    - job: pre-kaniko
      artifacts: true
.semver_template_defaults:
  stage: release
  
pre-kaniko:
  image: alpine:latest@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c
  stage: build
  variables:
    GIT_STRATEGY: clone
  before_script:
    - apk add git
  script: 
    - git pull origin $CI_COMMIT_REF_NAME --tags
    - echo "REPO_VERSION=$(git tag | sort -rV | head -1)-${CI_COMMIT_SHORT_SHA}" > version.env
  artifacts: 
    reports:
      dotenv: version.env


review::start:
  stage: review
  needs:
    - job: kaniko-build
      artifacts: false
review::stop:
  stage: review

integration test:
  stage: review
  needs:
    - job: review::start
      artifacts: true
  image: debian:sid@sha256:2b6042adb663a5a428aecf38779aac5fd8c2ef25fa2329612e0357d35c4add24
  variables:
    TERM: "xterm-256color"
  before_script:
    - apt-get update >/dev/null && apt-get install -y bats curl >/dev/null
    - mkdir -p reports
  script:
    - bats --formatter tap13 --report-formatter junit ./test/IntegrationTest/*.bats --output reports/ -T
  artifacts:
    when: always
    reports:
      junit: reports/*.xml
