---
stages:
  - test
  - build
  - review
  - release

include:
  - { project: fsrvcorp/templates, file: templates/language/dotnet.yml, ref: 1.0.2 }
  - { project: fsrvcorp/templates, file: templates/release/kaniko.yml, ref: 1.0.2 }
  - { project: fsrvcorp/templates, file: templates/release/semver.yml, ref: 1.0.2 }
  - { project: fsrvcorp/ci-templates, file: kubernetes-review.yaml }

variables:
  KUBE_BASE_DIR: "${CI_PROJECT_DIR}/test/IntegrationTest/.kube"
  KANIKO_ARGS: --context ${CI_PROJECT_DIR}/src/GitlabChamp --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} --build-arg REPO_VERSION=${REPO_VERSION}
  CONTAINER_FILE_LOCATION: ${CI_PROJECT_DIR}/src/GitlabChamp/Dockerfile
  SEMVER_PREFIX: "v"

.dotnet_template_defaults:
  stage: test
.kaniko_template_defaults:
  stage: build
  needs:
    - job: pre-kaniko
      artifacts: true
.semver_template_defaults:
  stage: release
  
pre-kaniko:
  image: alpine:latest@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978
  stage: build
  before_script:
    - apk add git
  script: 
    - echo "REPO_VERSION=$(git describe --tags --always)" > version.env
  artifacts: 
    reports:
      dotenv: version.env


review::start:
  stage: review
  needs:
    - job: kaniko-build
      artifacts: false
review::stop:
  stage: review


